### ISSUE TITLE
Question: Is there any way to get the live stream?

### ISSUE THREAD

**Issue by erickythierry** [surfzoid/HikNetExtractor#2]
I liked your project, with it I was able to find hosts to access the recordings.
but I would like to know if there is any way I can get the live preview?

for some reason my dvr doesn't work via rtsp, so I'm looking for another way to access the live view to create an automation. would you have any tips for me?

**Comment by surfzoid** [comment]
hi,
you need to setup video stream as mjpeg and then httppreviw will work, but if from chrome or firefox you have live view, check port, firewall, router config.
In my GitHub, you have QtVsPlayer, you can try, at least, there is my hikrtsp project, is alpha but can give you clues to understand

**Comment by surfzoid** [comment]
In HikRtsp, i tested live view with my own implementation of rtsp protocole and also with nethik sdk, now i would like to duplicate the way of linux webcomponent by using the sdk protocol but need more reverse engeniering to get /SDK/play/104 working
